name: HexoBlogFiles CI Trigger

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.0.0
      with: 
        key: ${{ secrets.actionGithubRepoDispatchToken }}
        repository: infiWang/HexoBlogFiles
        event-type: updatedSource
