name: HexoBlogFiles CI Trigger

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        tokenGithub: ${{ secrets.tokenGithubRepo }}

    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.0.0
      with: 
        token: ${{ matrix.tokenGithub }}
        repository: infiWang/HexoBlogFiles
        event-type: updatedSource
